---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: akaremii-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - matinlotfali/KDE-Rounded-Corners
        - scujas/plasma-applet-appgrid
    install:
      packages:
        - micro
        - starship
        - cava
        - kwin-effect-roundcorners
        - plasma-applet-appgrid
        - python-websockets
        - qt6-qtwebsockets-devel
        - https://github.com/samuelngs/apple-emoji-ttf/releases/download/macos-26-20260613-f1fc560b/fonts-apple-color-emoji.rpm

    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: os-release
    properties:
      NAME: "Akaremii OS"
      ID: "akaremii-os"
      ID_LIKE: "fedora"
      PRETTY_NAME: "Akaremii OS"
      HOME_URL: "https://github.com/akaremii26/akaremii-os"
      DOCUMENTATION_URL: "https://github.com/akaremii26/akaremii-os"
      SUPPORT_URL: "https://github.com/akaremii26/akaremii-os"
      BUG_REPORT_URL: "https://github.com/akaremii26/akaremii-os/issues/"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
