---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: akaremii-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: system-files.yml
  - from-file: packages.yml
  - from-file: kwin-rounded-corners.yml
#  - from-file: krema.yml
  - from-file: bazzite-cleanup.yml
  - from-file: vmware-dependencies.yml
  - from-file: os-release-config.yml
  - from-file: vmware-modules.yml
  - from-file: vmware-userspace.yml
  - from-file: vmware-remove-bundled-libs.yml
  - from-file: vmware-dkms.yml
  - from-file: vmware-systemd.yml
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
